components:
  schemas:
    BaseRequest:
      description: 'The required information for all Filesystem handler endpoints.


        key: unique

        item_path: destination path for the acting filesystem'
      properties:
        item_path:
          description: Acting path in filesystem
          title: Path
          type: string
        key:
          description: Unique identifier given as the filesystem 'name' in the config
            file
          title: Filesystem name
          type: string
      required:
      - key
      - item_path
      title: BaseRequest
      type: object
    DeleteRequest:
      description: 'Placeholder model for delete request


        No additional information is needed than base request'
      properties:
        item_path:
          description: Acting path in filesystem
          title: Path
          type: string
        key:
          description: Unique identifier given as the filesystem 'name' in the config
            file
          title: Filesystem name
          type: string
      required:
      - key
      - item_path
      title: DeleteRequest
      type: object
    Direction:
      enum:
      - upload
      - download
      title: Direction
      type: string
    GetRequest:
      description: 'GET request specific items.


        type: option to specify type of GET request'
      properties:
        item_path:
          description: Acting path in filesystem
          title: Path
          type: string
        key:
          description: Unique identifier given as the filesystem 'name' in the config
            file
          title: Filesystem name
          type: string
        type:
          anyOf:
          - $ref: '#/components/schemas/RequestType'
          - type: 'null'
          default: default
          description: Either a 'range' GET request for file or 'default' for normal
            GET
          title: Type of GET request
      required:
      - key
      - item_path
      title: GetRequest
      type: object
    PostRequest:
      description: 'POST request specific items.


        content: content to be created upon request

        action: move action specified when calling action handler'
      properties:
        action:
          anyOf:
          - $ref: '#/components/schemas/RequestAction'
          - type: 'null'
          default: null
          description: Specify 'move' action when calling action handler, default
            treated as copy
          title: Move or copy action indicator
        content:
          anyOf:
          - type: string
          - type: 'null'
          default: null
          description: Content to be created upon request
          title: File content or file/directory name
        item_path:
          description: Acting path in filesystem
          title: Path
          type: string
        key:
          description: Unique identifier given as the filesystem 'name' in the config
            file
          title: Filesystem name
          type: string
      required:
      - key
      - item_path
      title: PostRequest
      type: object
    RequestAction:
      const: move
      title: RequestAction
      type: string
    RequestType:
      enum:
      - default
      - range
      title: RequestType
      type: string
    TransferRequest:
      description: 'Requests made to download, upload and sync.


        key: unique

        destination_key: unique

        local_path: file/directory path, filesystem root path for sync

        remote_path: file/directory path, filesystem root path for sync

        action: enum option upload or download'
      properties:
        action:
          allOf:
          - $ref: '#/components/schemas/Direction'
          description: Can be 'upload' or 'download for local to remote or remote
            to local respectively
          title: Transfer direction
        destination_key:
          description: Unique identifier given as the filesystem 'name' in the config
            file
          title: Destination filesystem name
          type: string
        key:
          description: Unique identifier given as the filesystem 'name' in the config
            file
          title: Source filesystem name
          type: string
        local_path:
          title: Local Path
          type: string
        remote_path:
          title: Remote Path
          type: string
      required:
      - key
      - destination_key
      - local_path
      - remote_path
      - action
      title: TransferRequest
      type: object
info:
  title: jupyter-fsspec API
  version: 0.4.0
openapi: 3.1.1
