openapi: 3.1.0
info:
  title: jupyter-fsspec API
  version: 0.4.0
paths:
  /jupyter_fsspec/config:
    get:
      description: List all source filesystems in configuration file
      operationId: listConfigSources
      responses:
        '200':
          description: Retrieved available filesystems from configuration file.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Config'
components:
  schemas:
    BaseRequest:
      properties:
        key:
          type: string
          title: Filesystem name
          description: Unique identifier given as the filesystem 'name' in the config
            file
        item_path:
          type: string
          title: Path
          description: Acting path in filesystem
      type: object
      required:
      - key
      - item_path
      title: BaseRequest
      description: 'The required information for all Filesystem handler endpoints.


        key: unique

        item_path: destination path for the acting filesystem'
    DeleteRequest:
      properties:
        key:
          type: string
          title: Filesystem name
          description: Unique identifier given as the filesystem 'name' in the config
            file
        item_path:
          type: string
          title: Path
          description: Acting path in filesystem
      type: object
      required:
      - key
      - item_path
      title: DeleteRequest
      description: 'Placeholder model for delete request


        No additional information is needed than base request'
    Direction:
      type: string
      enum:
      - upload
      - download
      title: Direction
    GetRequest:
      properties:
        key:
          type: string
          title: Filesystem name
          description: Unique identifier given as the filesystem 'name' in the config
            file
        item_path:
          type: string
          title: Path
          description: Acting path in filesystem
        type:
          anyOf:
          - $ref: '#/components/schemas/RequestType'
          - type: 'null'
          title: Type of GET request
          description: Either a 'range' GET request for file or 'default' for normal
            GET
          default: default
      type: object
      required:
      - key
      - item_path
      title: GetRequest
      description: 'GET request specific items.


        type: option to specify type of GET request'
    PostRequest:
      properties:
        key:
          type: string
          title: Filesystem name
          description: Unique identifier given as the filesystem 'name' in the config
            file
        item_path:
          type: string
          title: Path
          description: Acting path in filesystem
        content:
          anyOf:
          - type: string
          - type: 'null'
          title: File content or file/directory name
          description: Content to be created upon request
        action:
          anyOf:
          - $ref: '#/components/schemas/RequestAction'
          - type: 'null'
          title: Move or copy action indicator
          description: Specify 'move' action when calling action handler, default
            treated as copy
      type: object
      required:
      - key
      - item_path
      title: PostRequest
      description: 'POST request specific items.


        content: content to be created upon request

        action: move action specified when calling action handler'
    RequestAction:
      type: string
      const: move
      title: RequestAction
    RequestType:
      type: string
      enum:
      - default
      - range
      title: RequestType
    TransferRequest:
      properties:
        key:
          type: string
          title: Source filesystem name
          description: Unique identifier given as the filesystem 'name' in the config
            file
        destination_key:
          type: string
          title: Destination filesystem name
          description: Unique identifier given as the filesystem 'name' in the config
            file
        local_path:
          type: string
          title: Local Path
        remote_path:
          type: string
          title: Remote Path
        action:
          allOf:
          - $ref: '#/components/schemas/Direction'
          title: Transfer direction
          description: Can be 'upload' or 'download for local to remote or remote
            to local respectively
      type: object
      required:
      - key
      - destination_key
      - local_path
      - remote_path
      - action
      title: TransferRequest
      description: 'Requests made to download, upload and sync.


        key: unique

        destination_key: unique

        local_path: file/directory path, filesystem root path for sync

        remote_path: file/directory path, filesystem root path for sync

        action: enum option upload or download'
    Config:
      properties:
        sources:
          items:
            $ref: '#/components/schemas/Source'
          type: array
          title: Sources
      type: object
      required:
      - sources
      title: Config
      description: A list of source filesystem configurations
    Source:
      properties:
        name:
          type: string
          title: Name
        path:
          type: string
          title: Path
        protocol:
          anyOf:
          - type: string
          - type: 'null'
          title: Protocol
        args:
          anyOf:
          - items: {}
            type: array
          - type: 'null'
          title: Args
          default: []
        kwargs:
          anyOf:
          - type: object
          - type: 'null'
          title: Kwargs
          default: {}
      type: object
      required:
      - name
      - path
      title: Source
      description: Filesystem configurations passed to fsspec
