name: Run API Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Base Setup
      uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

    - name: Install dependencies
      run: |
        python -m pip install -U "jupyterlab>=4.0.0,<5"
        pip install .[test]

    - name: API Tests
      run: |
        cd jupyter_fsspec/tests
        pytest -s -v
