name: PyPI Publish Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    environment: pypi-publish
    permissions:
      id-token: write
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
