name: Base Bump Version Setup

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  setup-bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Base Setup
        uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
        with:
          extra-packages: build hatch

      - name: Validate Version
        run: |
          if [[ ! "${{ inputs.version }}" =~ ^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(\.(0|[1-9][0-9]*))?([.-]?(a|b|rc)(0|[1-9][0-9]*))?$ ]]; then
            echo "Invalid version format. Please use semantic versioning (e.g., 0.1.2 or 0.1.2a1)"
            exit 1
          fi

      - name: Display version
        run: |
          echo "The entered version is: ${{ inputs.version }}"
